# Generated by Django 3.0.6 on 2021-05-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unsc', '0002_compliance_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_officer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_regulator',
            field=models.BooleanField(default=False),
        ),
    ]
