# Generated by Django 3.0.6 on 2021-05-25 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unsc', '0003_auto_20210525_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complianceofficer',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='unsc.Company'),
        ),
    ]
