# Generated by Django 3.2 on 2021-05-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unsc', '0005_auto_20210527_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='unscmemotablefunction',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
