# Generated by Django 3.2 on 2021-05-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unsc', '0006_unscmemotablefunction_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unscmemotablefunction',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
