# Generated by Django 3.2 on 2021-05-29 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unsc', '0007_alter_unscmemotablefunction_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='unsc.companytype'),
        ),
        migrations.AlterField(
            model_name='company',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='companytype',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='compliance',
            name='officer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='unsc.complianceofficer'),
        ),
        migrations.AlterField(
            model_name='complianceofficer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='power_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='complianceofficer',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='positivecompliance',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='positivecompliance',
            name='officer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='unsc.complianceofficer'),
        ),
        migrations.AlterField(
            model_name='regulator',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='unsclist',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
