# Generated by Django 3.2 on 2021-05-29 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unsc', '0008_auto_20210529_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='comp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='unsc.company'),
        ),
    ]
