# Generated by Django 3.2 on 2021-05-29 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unsc', '0009_user_comp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='comp',
            new_name='business_name',
        ),
    ]
