# Generated by Django 3.2 on 2021-05-29 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unsc', '0010_rename_comp_user_business_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cellphone_number',
            field=models.CharField(default=72000000, max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='work_number',
            field=models.CharField(default=3650000, max_length=64),
        ),
    ]
